/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 wumpus.glb -t -k
Author: aggy (https://sketchfab.com/jackagutter)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wumpus-5b6853575aaf48259b480561003df00c
Title: Wumpus
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    polySurface1_lambert14_0: THREE.Mesh;
    polySurface2_lambert4_0: THREE.Mesh;
    polySurface2_lambert7_0: THREE.Mesh;
    polySurface2_lambert8_0: THREE.Mesh;
    polySurface2_lambert9_0: THREE.Mesh;
    polySurface2_lambert10_0: THREE.Mesh;
    polySurface2_phong3_0: THREE.Mesh;
    pPlane1_lambert17_0: THREE.Mesh;
    pPlane2_lambert17_0: THREE.Mesh;
    pPlane3_lambert17_0: THREE.Mesh;
    pPlane4_lambert17_0: THREE.Mesh;
  };
  materials: {
    lambert14: THREE.MeshStandardMaterial;
    lambert4: THREE.MeshStandardMaterial;
    lambert7: THREE.MeshStandardMaterial;
    lambert8: THREE.MeshStandardMaterial;
    lambert9: THREE.MeshStandardMaterial;
    lambert10: THREE.MeshStandardMaterial;
    phong3: THREE.MeshStandardMaterial;
    lambert17: THREE.MeshStandardMaterial;
  };
};

export function WumpusModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/wumpus.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        name="Sketchfab_model"
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <group
          name="a727f48a4b394a39b39d8e03130cff85fbx"
          rotation={[Math.PI / 2, 0, 0]}
        >
          <group name="pCube15" position={[-1.05, -9.22, -0.01]} scale={11.79}>
            <group name="polySurface2" position={[0, -3.64, 0]} scale={3}>
              <mesh
                name="polySurface2_lambert4_0"
                geometry={nodes.polySurface2_lambert4_0.geometry}
                material={materials.lambert4}
              />
              <mesh
                name="polySurface2_lambert7_0"
                geometry={nodes.polySurface2_lambert7_0.geometry}
                material={materials.lambert7}
              />
              <mesh
                name="polySurface2_lambert8_0"
                geometry={nodes.polySurface2_lambert8_0.geometry}
                material={materials.lambert8}
              />
              <mesh
                name="polySurface2_lambert9_0"
                geometry={nodes.polySurface2_lambert9_0.geometry}
                material={materials.lambert9}
              />
              <mesh
                name="polySurface2_lambert10_0"
                geometry={nodes.polySurface2_lambert10_0.geometry}
                material={materials.lambert10}
              />
              <mesh
                name="polySurface2_phong3_0"
                geometry={nodes.polySurface2_phong3_0.geometry}
                material={materials.phong3}
              />
            </group>
            <mesh
              name="polySurface1_lambert14_0"
              geometry={nodes.polySurface1_lambert14_0.geometry}
              material={materials.lambert14}
              position={[0, -3.64, -0.26]}
              scale={3}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/wumpus.glb");
