/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./scene.gltf --transform --types
Author: Monster (https://sketchfab.com/wearemonsters)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coin-7d9b49c9ede348eab0a4ccaf46b3a44f
Title: Coin
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_8: THREE.Mesh;
  };
  materials: {
    ["gold_coin_texture.png"]: THREE.MeshStandardMaterial;
  };
};

export function Coin(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/coin.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials["gold_coin_texture.png"]}
        position={[4, 9.5, 15]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials["gold_coin_texture.png"]}
        position={[4, 9.5, 15]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials["gold_coin_texture.png"]}
        position={[13.5, 8, 15]}
      />
    </group>
  );
}

useGLTF.preload("/scene-transformed.glb");
